[package]
name = "rust-planner"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4", features = ["clock"] }
chrono-tz = "0.10"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

